### ISSUE TITLE
Getting errors and plugin undetected

### ISSUE THREAD

**Issue by ProjektRED267** [Kirezar/EasySwitchVita#1]
![img_3458](https://user-images.githubusercontent.com/42569134/44508252-35c83b00-a6e0-11e8-894c-7a276aef8f5b.JPG)

I'm getting the error upon startup but sometimes it will open fine. As for the plugins my ds4vita and minivitatv plugins is not detected. All my plugins is inside ur0:tai. I'm using Slim 3.65 H-Encore enso.

**Comment by Kirezar** [comment]
Thanks for the report, can you show me what is in your ur0:tai/ folder as well as your config.txt, and your ez_config.txt as well, that can be found in ux0:data/EasySwitchVita/ez_config.txt

**Comment by ProjektRED267** [comment]
Sorry for the late reply I've been a bit busy with work.

(ez_config.txt)
udcd_uvc=false
ds3=false
ds3vita=false
ds4vita=false
minivitatv=false
reboot_timer=3
auto_reboot=false

(config.txt)
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/storagemgr.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/repatch.skprx
ur0:tai/kuio.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/nopsmdrm.skprx
ur0:tai/noavls.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*!PSPEMUCFW
*!PCSE00692
*!PKGJ00000
*!EZSV00001
*ALL
ur0:tai/oclockvita.suprx
ur0:tai/VitaGrafix.suprx
ur0:tai/Framecounter.suprx
*main
ur0:tai/shellsecbat.suprx
ur0:tai/download_enabler.suprx
ur0:tai/pngshot.suprx
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx


![img_3543](https://user-images.githubusercontent.com/42569134/44616621-ad839a80-a885-11e8-9aac-d9a05a4958af.JPG)
![img_3544](https://user-images.githubusercontent.com/42569134/44616623-b2e0e500-a885-11e8-9812-e83338fd7810.JPG)

**Comment by Kirezar** [comment]
It doesn't seem like you have any of the supported plugins on your config.txt file. Try adding them to it and see if it crashes. Also try the version 1.01, it should help with some crashes

**Comment by MVTTSUN** [comment]
I have the exact same error C2-12828-1
